"""Seed the database with demo routes, stops, buses and trips.

OWNER: Member 5 (temporarily, while Member 4 is unavailable).

    python -m simulation_ml.seed.seed          # create tables + seed if empty
    python -m simulation_ml.seed.seed --reset  # drop everything first

WHY THIS DATA LOOKS THE WAY IT DOES
-----------------------------------
The demo is "crowd-aware route recommendations": the passenger sees two
options between Rajajinagar and Majestic and picks between fast-but-packed
and slow-but-empty. That contrast only works if the seed deliberately creates
it, so:

    21A  fast  (9 min scheduled),   load 35/50 = 0.70 -> MED  yellow
    7B   slow  (13 min scheduled),  load 12/50 = 0.24 -> LOW  green
    3C   slowest (33 min),           load 52/60 = 0.87 -> HIGH red

7B is slower AND empty, 21A is faster AND packed. Neither dominates, which is
exactly the trade-off we want on screen.

DATA IS REAL
------------
Stop names and coordinates come from OpenStreetMap via Overpass, and every
route's polyline comes from the OSRM routing service. That geometry is stored
in route_shape_point, so the simulator drives along real roads and the map
draws the real route rather than straight lines between stop markers.

The result is committed to simulation_ml/data/real_routes.json by
`python -m simulation_ml.tools.build_real_routes`, which means seeding makes no
network calls and the demo runs offline.

Note the two contrasts above are measured on the DEMO JOURNEY (Rajajinagar ->
Majestic), not on each route end to end. 21A is the longer route overall
(51.6 km vs 7B's 29.9 km); what matters is which gets the passenger there
sooner, which is what the planner reports.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

# Allow both `python -m simulation_ml.seed.seed` and `python seed/seed.py`.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from simulation_ml.db.models import (  # noqa: E402
    Bus,
    Crowd,
    Route,
    RouteShapePoint,
    RouteStop,
    Schedule,
    SegmentStat,
    Stop,
    Trip,
    crowd_level_for,
    get_sessionmaker,
    reset_database,
    utcnow,
)

# ---------------------------------------------------------------------------
# Stops and route geometry: REAL Bengaluru data, not invented placeholders.
#
# Everything below is loaded from simulation_ml/data/real_routes.json, which is
# generated by simulation_ml/tools/build_real_routes.py from:
#
#   - stop names + coordinates : OpenStreetMap via the Overpass API
#   - road geometry between them: OSRM
#
# That file is committed, so seeding performs NO network calls. Re-run the tool
# only to re-author the route layout.
#
# The previous hand-written coordinates were wrong: "Airport Road" sat near KR
# Market, ~25 km from the actual airport. Do not hand-edit coordinates here.
# ---------------------------------------------------------------------------
DATA_FILE = Path(__file__).resolve().parents[1] / "data" / "real_routes.json"

# Timetable speed per route, km/h. This is what makes the demo tell a story:
# 21A is a fast express, 7B is a slow one, 3C is the slowest and most crowded.
# Offsets and planned durations are DERIVED from real road distance using
# these, so they stay internally consistent with the geometry.
ROUTE_TIMETABLE_KMH = {
    "21A": 24.0,
    "7B": 17.0,
    "3C": 20.0,
}

# Observed / scheduled factor per leg: how much slower the road actually is.
# Length must be (number of stops - 1); it is validated at load time.
ROUTE_FACTORS = {
    "21A": [1.02, 1.05, 1.10, 1.08, 1.25, 1.35, 1.20, 1.15],
    "7B": [1.15, 1.30, 1.22, 1.28, 1.18, 1.35, 1.30, 1.25],
    "3C": [1.20, 1.40, 1.25, 1.18, 1.45, 1.22, 1.38, 1.28, 1.15, 1.30],
}

# Fraction of stops that are wheelchair accessible. Real BMTC accessibility is
# mixed; a couple of low-floor vehicles are flagged so the badges have something
# to render.
_ACCESSIBLE_CODES = {"STOP_RAJAJINAGAR", "STOP_MAJESTIC", "STOP_MG_ROAD", "STOP_BRIGADE_ROAD"}


def _load_real_routes() -> tuple[dict, list[dict]]:
    """Return (stops_by_code, route_specs) with offsets derived from geometry."""
    data = json.loads(DATA_FILE.read_text(encoding="utf-8"))

    stops: dict[str, tuple] = {}
    specs: list[dict] = []

    for r in data["routes"]:
        code = r["code"]
        factors = ROUTE_FACTORS[code]
        if len(factors) != len(r["legs"]):
            raise ValueError(
                f"{code}: {len(factors)} factors for {len(r['legs'])} legs - "
                f"ROUTE_FACTORS is out of date"
            )

        kmh = ROUTE_TIMETABLE_KMH[code]
        mps = kmh * 1000.0 / 3600.0

        stop_rows: list[tuple] = []
        offset = 0.0
        for i, st in enumerate(r["stops"]):
            if i > 0:
                offset += r["legs"][i - 1]["metres"] / mps
            stops[st["code"]] = (
                st["code"], st["name"], st["lat"], st["lon"],
                st["code"] in _ACCESSIBLE_CODES,
            )
            stop_rows.append((st["code"], int(round(offset))))

        specs.append({
            "code": code,
            "name": r["name"],
            "direction": "up",
            "stops": stop_rows,
            "factors": factors,
            "duration_sec": int(round(offset)),
            "shape": r["legs"],
        })

    # A stop can appear on several routes (Majestic is on all three), so collect
    # into a dict keyed by code and hand the seed a de-duplicated list of tuples.
    return list(stops.values()), specs


STOPS, ROUTES = _load_real_routes()

# The journey the demo opens on. Both codes are real stops that appear on more
# than one route, so the planner returns two options and the fast-vs-slow
# trade-off the demo is built around still lands.
DEMO_JOURNEY = ("STOP_RAJAJINAGAR", "STOP_MAJESTIC")

# Fail loudly at import if the demo journey would not produce two options.
_shared = [
    c for c, spec in ((r["code"], r) for r in ROUTES)
    if all(code in {s[0] for s in spec["stops"]} for code in DEMO_JOURNEY)
]
if len(_shared) < 2:
    raise ValueError(
        f"DEMO_JOURNEY {DEMO_JOURNEY} is only usable on {_shared}; "
        f"the demo needs at least two routes sharing both stops"
    )

def haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Great-circle distance in metres. Used to accumulate shape cum_m."""
    r = 6_371_000.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(a))


# ---------------------------------------------------------------------------
# Buses  ->  (reg_no, capacity, wheelchair, low_floor)
# ---------------------------------------------------------------------------
BUSES = [
    ("KA01AB1234", 50, True, True),    # bus 1 -> 21A trip  (crowded, accessible)
    ("KA01AB5678", 50, False, False),  # bus 2 -> 7B trip   (empty, basic)
    ("KA05CD9012", 60, True, True),    # bus 3 -> 3C trip
    ("KA05CD3456", 50, False, True),   # bus 4 -> spare / out of service demo
]

# ---------------------------------------------------------------------------
# Trips.  seed_load is the headline demo number.
# ---------------------------------------------------------------------------
TRIPS = [
    # (bus_index, route_code, seed_load)
    (0, "21A", 35),  # 35/50 = 0.70 -> MED   the crowded fast option
    (1, "7B", 12),   # 12/50 = 0.24 -> LOW   the empty slow option
    (2, "3C", 52),   # 52/60 = 0.87 -> HIGH  proves the red band renders
]

# Start each trip a little way along so buses are already moving on first run.
INITIAL_PROGRESS = {
    "21A": 0.28,
    "7B": 0.15,
    "3C": 0.40,
}


def seed(reset: bool = False, url: str | None = None) -> None:
    Session = get_sessionmaker(url)
    engine_url = url or None

    if reset:
        print("Dropping and recreating all tables ...")
        reset_database(engine_url)

    # create_all is idempotent
    from simulation_ml.db.models import create_all

    create_all(engine_url)

    with Session() as s:
        if s.query(Route).count() > 0:
            print("Database already seeded - skipping. Use --reset to rebuild.")
            return

        # ---- stops ------------------------------------------------------
        stop_by_code: dict[str, Stop] = {}
        for code, name, lat, lon, accessible in STOPS:
            st = Stop(code=code, name=name, lat=lat, lon=lon, accessible=accessible)
            s.add(st)
            stop_by_code[code] = st
        s.flush()
        print(f"  stops   {len(STOPS)}")

        # ---- buses ------------------------------------------------------
        bus_objs = [
            Bus(reg_no=reg, capacity=cap, wheelchair=wc, low_floor=lf)
            for reg, cap, wc, lf in BUSES
        ]
        for b in bus_objs:
            s.add(b)
        s.flush()
        print(f"  buses   {len(bus_objs)}")

        # ---- routes + route_stop + schedule offsets + segment stats -----
        route_by_code: dict[str, Route] = {}
        total_segments = 0
        total_shape_points: dict[str, float] = {}
        for spec in ROUTES:
            rt = Route(code=spec["code"], name=spec["name"], direction=spec["direction"])
            s.add(rt)
            s.flush()
            route_by_code[spec["code"]] = rt

            stops = spec["stops"]
            factors = spec["factors"]

            for seq, (stop_code, offset) in enumerate(stops):
                s.add(
                    RouteStop(
                        route_id=rt.id,
                        stop_id=stop_by_code[stop_code].id,
                        seq=seq,
                        scheduled_offset_sec=offset,
                    )
                )

            # segment stats: observed = scheduled * factor for this hop.
            # factors[i] describes the segment LEAVING stop i.
            for seq in range(len(stops) - 1):
                sched_sec = stops[seq + 1][1] - stops[seq][1]
                total_segments += 1
                s.add(
                    SegmentStat(
                        route_id=rt.id,
                        from_stop_id=stop_by_code[stops[seq][0]].id,
                        to_stop_id=stop_by_code[stops[seq + 1][0]].id,
                        sched_travel_sec=sched_sec,
                        avg_travel_sec=float(sched_sec) * factors[seq],
                        samples=140 + seq * 15,
                        observed_at=utcnow(),
                    )
                )

            # Real road geometry. cum_m is the running distance from the very
            # first vertex of the route, so the simulator can convert a 0-1
            # progress fraction straight into a point on the shape.
            cum = 0.0
            prev_lat = prev_lon = None
            for leg_idx, leg in enumerate(spec["shape"]):
                for seq, (lat, lon) in enumerate(leg["coords"]):
                    if prev_lat is not None:
                        cum += haversine_m(prev_lat, prev_lon, lat, lon)
                    s.add(
                        RouteShapePoint(
                            route_id=rt.id, leg=leg_idx, seq=seq,
                            lat=lat, lon=lon, cum_m=cum,
                        )
                    )
                    prev_lat, prev_lon = lat, lon
            total_shape_points[spec["code"]] = int(cum)
        s.flush()
        print(f"  routes  {len(ROUTES)}  ({total_segments} segments with observed stats)")
        print(f"  shape   {sum(total_shape_points.values()) / 1000:.1f} km of real road geometry")

        # ---- trips ------------------------------------------------------
        now = utcnow()
        trip_by_route: dict[str, Trip] = {}
        for bus_idx, route_code, seed_load in TRIPS:
            spec = next(r for r in ROUTES if r["code"] == route_code)
            rt = route_by_code[route_code]
            bus = bus_objs[bus_idx]
            progress = INITIAL_PROGRESS.get(route_code, 0.0)

            tr = Trip(
                bus_id=bus.id,
                route_id=rt.id,
                direction=spec["direction"],
                status="active",
                started_at=now,
                planned_duration_sec=spec["duration_sec"],
            )
            s.add(tr)
            s.flush()
            trip_by_route[route_code] = tr

            # timetable rows for the whole trip
            for stop_code, offset in spec["stops"]:
                s.add(
                    Schedule(
                        trip_id=tr.id,
                        stop_id=stop_by_code[stop_code].id,
                        scheduled_offset_sec=offset,
                        scheduled_arrival=None,
                    )
                )

            # Seed a crowd row at the stop the bus is just leaving. This is the
            # number the API surfaces, so it must match the trip's story.
            route_stop_list = sorted(
                [rs for rs in rt.route_stops], key=lambda r: r.seq
            )
            current_seq = min(int(progress * len(route_stop_list)), len(route_stop_list) - 1)
            here = route_stop_list[current_seq]

            s.add(
                Crowd(
                    trip_id=tr.id,
                    stop_id=here.stop_id,
                    load=seed_load,
                    capacity=bus.capacity,
                    level=crowd_level_for(seed_load, bus.capacity),
                    ts=now,
                )
            )

            # One telemetry tick so /api/buses/active is non-empty immediately,
            # before the simulator is ever started.
            stops_ordered = route_stop_list
            frac = progress * (len(stops_ordered) - 1)
            i = min(int(frac), len(stops_ordered) - 2)
            t = frac - i
            a, b = stops_ordered[i].stop, stops_ordered[i + 1].stop
            from simulation_ml.db.models import Location

            s.add(
                Location(
                    bus_id=bus.id,
                    trip_id=tr.id,
                    lat=a.lat + (b.lat - a.lat) * t,
                    lon=a.lon + (b.lon - a.lon) * t,
                    speed_kmph=24.0,
                    heading=0.0,
                    seq_progress=progress,
                    ts=now,
                )
            )

        s.commit()
        print(f"  trips   {len(TRIPS)} (all active, with timetable + crowd + first tick)")

    print("\nSeed complete.")
    print("\n  Real Bengaluru data:")
    print(f"    {len(STOPS)} stops from OpenStreetMap, {sum(r['total_metres'] for r in json.loads(DATA_FILE.read_text(encoding='utf-8'))['routes']) / 1000:.0f} km of real road geometry (OSRM)")

    print("\n  Demo story baked in:")
    crowd_note = {"21A": "MED  35/50", "7B": "LOW  12/50", "3C": "HIGH 52/60 - red band"}
    for spec in ROUTES:
        code = spec["code"]
        mins = spec["duration_sec"] / 60.0
        print(f"    {code}  {mins:5.1f} min end to end, {crowd_note[code]}")

    demo_from, demo_to = DEMO_JOURNEY
    print(f"\n  Plan {demo_from} -> {demo_to} and you get two options.")
    print("  Next: python -m simulation_ml.simulate --speed 5 --interval 2")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Seed the RideSmart demo database")
    ap.add_argument(
        "--reset", action="store_true", help="drop all tables before seeding"
    )
    ap.add_argument("--url", default=None, help="override DATABASE_URL")
    args = ap.parse_args()
    seed(reset=args.reset, url=args.url)