"""Seed the database with demo routes, stops, buses and trips.

OWNER: Member 5 (temporarily, while Member 4 is unavailable).

    python -m simulation_ml.seed.seed          # create tables + seed if empty
    python -m simulation_ml.seed.seed --reset  # drop everything first

WHY THIS DATA LOOKS THE WAY IT DOES
-----------------------------------
The demo is "crowd-aware route recommendations": the passenger sees three
options between VIT and Vellore Old Bus Stand and picks between fast-but-packed
and slow-but-empty. All three routes run the same real spine (Kingston ->
Katpadi -> town centre), so they are genuine alternatives, and that contrast
only works if the seed deliberately creates it:

    V1  fast  (26 min scheduled),    load 35/50 = 0.70 -> MED  yellow
    M1  mid   (32 min scheduled),    load 52/60 = 0.87 -> HIGH red
    V2  slow  (40 min scheduled),    load 12/50 = 0.24 -> LOW  green

V2 is slower AND empty, V1 is faster AND packed. Neither dominates, which is
exactly the trade-off we want on screen.

DATA IS REAL
------------
The corridor is Vellore - Katpadi in Tamil Nadu, running from Kingston
Engineering College in the north down to Bagayam and Christian Medical College
in the south. Stop names and coordinates come from OpenStreetMap via Overpass,
and every route's polyline comes from the OSRM routing service. That geometry is
stored in route_shape_point, so the simulator drives along real roads and the map
draws the real route rather than straight lines between stop markers.

One stop is flagged kind="campus": Kingston Engineering College is a real place
OSM maps precisely, but there is no bus bay mapped there - the nearest named
bus stop is 4.2 km away at Palloor. Its pin sits at the college and is labelled
as a campus stop rather than passed off as a surveyed bus stand.

The result is committed to simulation_ml/data/real_routes.json by
`python -m simulation_ml.tools.build_real_routes`, which means seeding makes no
network calls and the demo runs offline.

Note the contrasts above are measured on the DEMO JOURNEY (VIT -> Vellore Old
Bus Stand), not on each route end to end. V2 is the shortest route overall
(24.3 km vs V1's 28.1 km) but the slowest per km, so it is the longest in time;
what matters is which gets the passenger there sooner, which is what the planner
reports.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

# Allow both `python -m simulation_ml.seed.seed` and `python seed/seed.py`.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from simulation_ml.db.models import (  # noqa: E402
    Bus,
    Crowd,
    Route,
    RouteShapePoint,
    RouteStop,
    Schedule,
    SegmentStat,
    Stop,
    Trip,
    crowd_level_for,
    get_sessionmaker,
    reset_database,
    utcnow,
)

# ---------------------------------------------------------------------------
# Stops and route geometry: REAL Vellore-Katpadi data, not invented placeholders.
#
# Everything below is loaded from simulation_ml/data/real_routes.json, which is
# generated by simulation_ml/tools/build_real_routes.py from:
#
#   - stop names + coordinates : OpenStreetMap via the Overpass API
#   - road geometry between them: OSRM
#
# That file is committed, so seeding performs NO network calls. Re-run the tool
# only to re-author the route layout.
#
# Do not hand-edit coordinates here: the generator refuses to run if a landmark
# can no longer be snapped to a real OSM node, which is what stops a plausible
# but wrong pin (a landmark in the wrong town) from ever reaching the database.
# ---------------------------------------------------------------------------
DATA_FILE = Path(__file__).resolve().parents[1] / "data" / "real_routes.json"

# Timetable speed per route, km/h. This is what makes the demo tell a story:
# V1 is a fast service, V2 is a slow one, M1 sits between and is the most
# crowded. Offsets and planned durations are DERIVED from real road distance
# using these, so they stay internally consistent with the geometry.
ROUTE_TIMETABLE_KMH = {
    "V1": 24.0,
    "V2": 17.0,
    "M1": 20.0,
}

# Observed / scheduled factor per leg: how much slower the road actually is.
# Length must be (number of stops - 1); it is validated at load time.
ROUTE_FACTORS = {
    "V1": [1.02, 1.05, 1.10, 1.08, 1.25, 1.35, 1.20, 1.15, 1.22, 1.18, 1.28, 1.12],
    "V2": [1.15, 1.30, 1.22, 1.28, 1.18, 1.35, 1.30, 1.25, 1.20, 1.26, 1.18],
    "M1": [1.20, 1.40, 1.25, 1.18, 1.45, 1.22, 1.38, 1.28, 1.15, 1.30, 1.20, 1.26, 1.18, 1.24],
}

# Fraction of stops that are wheelchair accessible. Accessibility on the real
# network is mixed; a couple of stops are flagged so the badges have something
# to render.
_ACCESSIBLE_CODES = {
    "STOP_VIT",
    "STOP_VELLORE_OLD_BUS_STAND",
    "STOP_KATPADI_JUNCTION",
    "STOP_CMC_HOSPITAL",
}


def _load_real_routes() -> tuple[dict, list[dict]]:
    """Return (stops_by_code, route_specs) with offsets derived from geometry."""
    data = json.loads(DATA_FILE.read_text(encoding="utf-8"))

    stops: dict[str, tuple] = {}
    specs: list[dict] = []

    for r in data["routes"]:
        code = r["code"]
        factors = ROUTE_FACTORS[code]
        if len(factors) != len(r["legs"]):
            raise ValueError(
                f"{code}: {len(factors)} factors for {len(r['legs'])} legs - "
                f"ROUTE_FACTORS is out of date"
            )

        kmh = ROUTE_TIMETABLE_KMH[code]
        mps = kmh * 1000.0 / 3600.0

        stop_rows: list[tuple] = []
        offset = 0.0
        for i, st in enumerate(r["stops"]):
            if i > 0:
                offset += r["legs"][i - 1]["metres"] / mps
            stops[st["code"]] = (
                st["code"], st["name"], st["lat"], st["lon"],
                st["code"] in _ACCESSIBLE_CODES, st.get("kind", "transit"),
            )
            stop_rows.append((st["code"], int(round(offset))))

        specs.append({
            "code": code,
            "name": r["name"],
            "direction": "up",
            "stops": stop_rows,
            "factors": factors,
            "duration_sec": int(round(offset)),
            "shape": r["legs"],
        })

    # A stop can appear on several routes (VIT is on all three), so collect
    # into a dict keyed by code and hand the seed a de-duplicated list of tuples.
    # The kind is carried through rather than flattened: a campus anchor is not
    # a surveyed bus bay, and the UI is told which is which.
    return list(stops.values()), specs


STOPS, ROUTES = _load_real_routes()

# The journey the demo opens on. Both codes are real stops that appear on more
# than one route, so the planner returns several options and the fast-vs-slow
# trade-off the demo is built around still lands.
DEMO_JOURNEY = ("STOP_VIT", "STOP_VELLORE_OLD_BUS_STAND")

# Fail loudly at import if the demo journey would not produce two options.
_shared = [
    c for c, spec in ((r["code"], r) for r in ROUTES)
    if all(code in {s[0] for s in spec["stops"]} for code in DEMO_JOURNEY)
]
if len(_shared) < 2:
    raise ValueError(
        f"DEMO_JOURNEY {DEMO_JOURNEY} is only usable on {_shared}; "
        f"the demo needs at least two routes sharing both stops"
    )

def haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Great-circle distance in metres. Used to accumulate shape cum_m."""
    r = 6_371_000.0
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = math.radians(lat2 - lat1)
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * r * math.asin(math.sqrt(a))


# ---------------------------------------------------------------------------
# Buses  ->  (reg_no, capacity, wheelchair, low_floor)
#
# display_name ("Bus 1"...) is assigned from position when inserted, never
# derived from reg_no: TN09AB1234 says nothing to anyone at a stop.
# ---------------------------------------------------------------------------
BUSES = [
    ("TN09AB1234", 50, True, True),    # bus 1 -> V1 trip  (crowded, accessible)
    ("TN09AB5678", 50, False, False),  # bus 2 -> V2 trip  (empty, basic)
    ("TN09CD9012", 60, True, True),    # bus 3 -> M1 trip
    ("TN09CD3456", 50, False, True),   # bus 4 -> spare / out of service demo
]

# ---------------------------------------------------------------------------
# Trips.  seed_load is the headline demo number.
# ---------------------------------------------------------------------------
TRIPS = [
    # (bus_index, route_code, seed_load)
    (0, "V1", 35),  # 35/50 = 0.70 -> MED   the crowded fast option
    (1, "V2", 12),  # 12/50 = 0.24 -> LOW   the empty slow option
    (2, "M1", 52),  # 52/60 = 0.87 -> HIGH  proves the red band renders
]

# Start each trip a little way along so buses are already moving on first run.
INITIAL_PROGRESS = {
    "V1": 0.28,
    "V2": 0.15,
    "M1": 0.40,
}


def seed(reset: bool = False, url: str | None = None, include_network: bool = False) -> None:
    """Create tables and seed the demo network.

    include_network adds the synthetic Vellore - Katpadi network from
    simulation_ml/seed/network_data.py: 29 route numbers in both directions, a
    96-vehicle fleet, through-the-day timetables and live trips for each bus.

    That is 100 buses with the three demo routes, the top of the brief's 60-100
    band. Busy city corridors get 4 buses and sparse ones 3, deliberately: with
    one bus per route a given origin sees a single candidate and the "least
    crowded" ranking has nothing to reorder, so the feature would be present in
    the API and absent from the product.

    It is OFF by default on purpose. Without it this function produces exactly
    the three-route, 23-stop demo the test-suite asserts on, so those assertions
    keep meaning what they say. Turn it on for the full network:

        python -m simulation_ml.seed.seed --reset --network
    """
    Session = get_sessionmaker(url)
    engine_url = url or None

    if reset:
        print("Dropping and recreating all tables ...")
        reset_database(engine_url)

    # create_all is idempotent
    from simulation_ml.db.models import create_all

    create_all(engine_url)

    with Session() as s:
        has_demo = s.query(Route).count() > 0
        # "Has the synthetic network been added?" is asked by looking for one of
        # the numbers the network actually declares. It used to be
        # route_number != "", which only worked while the three demo routes left
        # that column empty. They populate it now (V1/V2/M1), so the
        # old test reports a networked database after a plain demo seed and
        # silently skips --network. Naming the numbers is explicit and stays
        # correct whatever the demo routes carry.
        from simulation_ml.seed.network_data import ROUTE_SPECS

        network_numbers = {spec[0] for spec in ROUTE_SPECS}
        has_network = (
            s.query(Route).filter(Route.route_number.in_(network_numbers)).count() > 0
        )

        if has_demo:
            print("Database already seeded - skipping. Use --reset to rebuild.")
        else:

            # ---- stops ------------------------------------------------------
            stop_by_code: dict[str, Stop] = {}
            for code, name, lat, lon, accessible, kind in STOPS:
                st = Stop(code=code, name=name, lat=lat, lon=lon, accessible=accessible, kind=kind)
                s.add(st)
                stop_by_code[code] = st
            s.flush()
            print(f"  stops   {len(STOPS)}")

            # ---- buses ------------------------------------------------------
            # Numbered by position, and the number is a property of the FLEET,
            # not of this seed run: seed --network appends to the same database,
            # so it has to continue from however many buses already exist or two
            # vehicles would answer to "Bus 4". Fresh demo seed starts at 1.
            bus_objs = [
                Bus(
                    reg_no=reg,
                    display_name=f"Bus {i}",
                    capacity=cap,
                    wheelchair=wc,
                    low_floor=lf,
                )
                for i, (reg, cap, wc, lf) in enumerate(BUSES, start=1)
            ]
            for b in bus_objs:
                s.add(b)
            s.flush()
            print(f"  buses   {len(bus_objs)}")

            # ---- routes + route_stop + schedule offsets + segment stats -----
            route_by_code: dict[str, Route] = {}
            total_segments = 0
            total_shape_points: dict[str, float] = {}
            for spec in ROUTES:
                rt = Route(
                    code=spec["code"],
                    # `spec["code"]`, never the bare name `code`: that is the
                    # loop variable left over from the STOPS loop above, so using
                    # it here shipped the last stop's code ("STOP_CMC_CAMPUS") as
                    # every route's passenger-facing route number.
                    route_number=spec["code"],
                    name=spec["name"],
                    direction=spec["direction"],
                )
                s.add(rt)
                s.flush()
                route_by_code[spec["code"]] = rt

                stops = spec["stops"]
                factors = spec["factors"]

                # leg_distance_m is the real road length of the hop INTO this
                # stop, taken from the OSRM leg rather than recomputed, so the
                # planner's distance-based ETA matches the geometry the map
                # draws. Stops[0] is the origin and has no leg into it.
                legs = spec["shape"]
                for seq, (stop_code, offset) in enumerate(stops):
                    s.add(
                        RouteStop(
                            route_id=rt.id,
                            stop_id=stop_by_code[stop_code].id,
                            seq=seq,
                            scheduled_offset_sec=offset,
                            leg_distance_m=float(legs[seq - 1]["metres"]) if seq else 0.0,
                        )
                    )

                # segment stats: observed = scheduled * factor for this hop.
                # factors[i] describes the segment LEAVING stop i.
                for seq in range(len(stops) - 1):
                    sched_sec = stops[seq + 1][1] - stops[seq][1]
                    total_segments += 1
                    s.add(
                        SegmentStat(
                            route_id=rt.id,
                            from_stop_id=stop_by_code[stops[seq][0]].id,
                            to_stop_id=stop_by_code[stops[seq + 1][0]].id,
                            sched_travel_sec=sched_sec,
                            avg_travel_sec=float(sched_sec) * factors[seq],
                            samples=140 + seq * 15,
                            observed_at=utcnow(),
                        )
                    )

                # Real road geometry. cum_m is the running distance from the very
                # first vertex of the route, so the simulator can convert a 0-1
                # progress fraction straight into a point on the shape.
                cum = 0.0
                prev_lat = prev_lon = None
                for leg_idx, leg in enumerate(spec["shape"]):
                    for seq, (lat, lon) in enumerate(leg["coords"]):
                        if prev_lat is not None:
                            cum += haversine_m(prev_lat, prev_lon, lat, lon)
                        s.add(
                            RouteShapePoint(
                                route_id=rt.id, leg=leg_idx, seq=seq,
                                lat=lat, lon=lon, cum_m=cum,
                            )
                        )
                        prev_lat, prev_lon = lat, lon
                total_shape_points[spec["code"]] = int(cum)
            s.flush()
            print(f"  routes  {len(ROUTES)}  ({total_segments} segments with observed stats)")
            print(f"  shape   {sum(total_shape_points.values()) / 1000:.1f} km of real road geometry")

            # ---- trips ------------------------------------------------------
            now = utcnow()
            trip_by_route: dict[str, Trip] = {}
            for bus_idx, route_code, seed_load in TRIPS:
                spec = next(r for r in ROUTES if r["code"] == route_code)
                rt = route_by_code[route_code]
                bus = bus_objs[bus_idx]
                progress = INITIAL_PROGRESS.get(route_code, 0.0)

                tr = Trip(
                    bus_id=bus.id,
                    route_id=rt.id,
                    direction=spec["direction"],
                    status="active",
                    started_at=now,
                    planned_duration_sec=spec["duration_sec"],
                )
                s.add(tr)
                s.flush()
                trip_by_route[route_code] = tr

                # timetable rows for the whole trip
                for stop_code, offset in spec["stops"]:
                    s.add(
                        Schedule(
                            trip_id=tr.id,
                            stop_id=stop_by_code[stop_code].id,
                            scheduled_offset_sec=offset,
                            scheduled_arrival=None,
                        )
                    )

                # Seed a crowd row at the stop the bus is just leaving. This is the
                # number the API surfaces, so it must match the trip's story.
                route_stop_list = sorted(
                    [rs for rs in rt.route_stops], key=lambda r: r.seq
                )
                current_seq = min(int(progress * len(route_stop_list)), len(route_stop_list) - 1)
                here = route_stop_list[current_seq]

                s.add(
                    Crowd(
                        trip_id=tr.id,
                        stop_id=here.stop_id,
                        load=seed_load,
                        capacity=bus.capacity,
                        level=crowd_level_for(seed_load, bus.capacity),
                        ts=now,
                    )
                )

                # One telemetry tick so /api/buses/active is non-empty immediately,
                # before the simulator is ever started.
                stops_ordered = route_stop_list
                frac = progress * (len(stops_ordered) - 1)
                i = min(int(frac), len(stops_ordered) - 2)
                t = frac - i
                a, b = stops_ordered[i].stop, stops_ordered[i + 1].stop
                from simulation_ml.db.models import Location

                s.add(
                    Location(
                        bus_id=bus.id,
                        trip_id=tr.id,
                        lat=a.lat + (b.lat - a.lat) * t,
                        lon=a.lon + (b.lon - a.lon) * t,
                        speed_kmph=24.0,
                        heading=0.0,
                        seq_progress=progress,
                        current_stop_id=stops_ordered[i].stop_id,
                        next_stop_id=stops_ordered[i + 1].stop_id,
                        # A little behind the timetable, matching the
                        # ROUTE_FACTORS the segment stats are seeded with. Real
                        # observed times replace this within one tick once the
                        # simulator runs.
                        delay_sec=float(int(progress * spec["duration_sec"] * 0.08)),
                        ts=now,
                    )
                )

            s.commit()
            print(f"  trips   {len(TRIPS)} (all active, with timetable + crowd + first tick)")

    # ---- the synthetic network, after the OSM stops exist ----------------
    # Ordering matters: network_data reuses stop codes from data/real_routes.json
    # so the two networks share one connected graph rather than putting two pins
    # on Katpadi Junction. Those stops have to be in the table first.
    if include_network and not has_network:
        from simulation_ml.seed.seed_network import seed_network

        with Session() as s:
            print("\nSeeding the synthetic Vellore - Katpadi network ...")
            summary = seed_network(s)
            s.commit()
            print(
                f"  stops   +{summary['stops_created']} new "
                f"({summary['stops']} synthetic, {summary['reused_stops']} reused from OSM)"
            )
            print(
                f"  routes  +{summary['routes_written']} "
                f"({summary['route_numbers']} numbers x 2 directions)"
            )
            print(f"  buses   +{summary['buses']} ({summary['accessible_buses']} wheelchair accessible)")
            print(f"  trips   +{summary['active_trips']} active, with timetable + crowd + first tick")
            print(f"  shape   {summary['shape_points']} approximate vertices, {summary['segments']} segments")
            print("  NOTE    synthetic data. Stop names and coordinates are real places;")
            print("          route numbers, fleet and headways are invented, not TNSTC data.")

    print("\nSeed complete.")
    print("\n  Real Vellore - Katpadi data:")
    print(f"    {len(STOPS)} stops from OpenStreetMap, {sum(r['total_metres'] for r in json.loads(DATA_FILE.read_text(encoding='utf-8'))['routes']) / 1000:.0f} km of real road geometry (OSRM)")
    campus = [code for code, _name, _lat, _lon, _acc, kind in STOPS if kind == "campus"]
    if campus:
        print(f"    campus anchor (not a surveyed bus bay): {', '.join(campus)}")

    print("\n  Demo story baked in:")
    crowd_note = {"V1": "MED  35/50", "V2": "LOW  12/50", "M1": "HIGH 52/60 - red band"}
    for spec in ROUTES:
        code = spec["code"]
        mins = spec["duration_sec"] / 60.0
        print(f"    {code}  {mins:5.1f} min end to end, {crowd_note[code]}")

    demo_from, demo_to = DEMO_JOURNEY
    print(f"\n  Plan {demo_from} -> {demo_to} and you get three options.")
    print("  Next: python -m simulation_ml.simulate --speed 5 --interval 2")

    if include_network:
        # The hint above describes POST /api/routes/plan, which is the
        # route-level planner and still the right answer for "compare these
        # corridors". The app itself plans with GET /api/journey, which returns
        # BUSES. Leaving only the older hint would point at an endpoint nothing
        # in the UI calls, so both are named - and the difference between them is
        # the whole point of having two.
        print("\n  Two planners, different questions:")
        print("    GET  /api/journey?from_stop_id=4&to_stop_id=8   the BUSES you can catch")
        print("    POST /api/routes/plan  {from,to}               the ROUTES to weigh up")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Seed the RideSmart demo database")
    ap.add_argument(
        "--reset", action="store_true", help="drop all tables before seeding"
    )
    ap.add_argument(
        "--network",
        action="store_true",
        help="also seed the synthetic Vellore - Katpadi network "
             "(29 route numbers in both directions, 91 buses, timetables, live trips)",
    )
    ap.add_argument("--url", default=None, help="override DATABASE_URL")
    args = ap.parse_args()
    seed(reset=args.reset, url=args.url, include_network=args.network)
